name: A testing workflow action yml
on: push

jobs:
  build:
    name: Dockerize
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
      -
        uses: docker/login-action@v1
        with:
          registry: waltercheng
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: set up Docker Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: waltercheng/gin_backend:latest
      - 
        name: Testing SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export WORKING_PATH=${{ secrets.WORKING_PATH }}
            cd $WORKING_PATH
            ls 
            docker-compose down
            docker-compose up -d


        
