name: A testing workflow action yml
on: push

jobs:
  build:
    name: Dockerize
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: set up Docker Buildx
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: waltercheng/gin_backend
          tag_with_ref: true
      - 
        name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts : ${{ secrets.SERVER_IP }}
      - 
        name: testing SSH
        run: ls -a

        
