name: A testing workflow action yml
on: push

jobs:
  build:
    name: Dockerize
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v1
      -
        name: set up Docker Buildx
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: waltercheng/gin_backend
          tag_with_ref: true

        
